
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      version: "2.4.1"
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: t3n
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer