
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      version: "5.0.20"
      chart: truecharts/mosquitto
      sourceRef:
        kind: HelmRepository
        name: truecharts
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
